snippet deletion functinality
Hexlet/runit pull request #32
Opened 2022-11-03 05:47 UTC by Takaiva

- added function to delete snippets
- added notification about existing user when registering
- added deletion handler
enhancement #25

2022-11-04 05:35 UTC, dzencot requested changes

2022-11-04 05:35 UTC, dzencot commented on app/javascript/Pages/Profile.jsx
> +    const response = await axios.get(routes.userProfilePath());
Зачем делать запрос на получение снипетов? У нас же уже есть список, и мы можем из него удалить этот снипет.

2022-11-07 17:01 UTC, dzencot commented on app/javascript/Pages/Profile.jsx
> +  }, [snippets]);
А тут зачем в зависимостях снипеты?

2022-11-07 17:14 UTC, Takaiva commented on app/javascript/Pages/Profile.jsx
> +  }, [snippets]);
Странно, у меня багнулось видимо. Казалось, без этого в real time не перерисовывается.

2022-11-07 17:20 UTC, Takaiva commented on app/javascript/Pages/Profile.jsx
> +  }, [snippets]);
Хотя теперь все логично

2022-11-07 18:20 UTC, merged