Issue[#52][#50] Delete burger menu and change logo
Hexlet/runit pull request #57
Opened 2022-11-13 10:00 UTC by Wenn911

2022-11-14 15:05 UTC, dzencot requested changes

2022-11-14 15:05 UTC, dzencot commented on app/javascript/components/Navbar.jsx
> +import Logo from '../../assets/landing/images/blacklogo.png'
Давай тут заменим путь на `/app/assets/landing/images/blacklogo.png`. Это избавит от проблем, если изменится структура компонентов.

2022-11-14 20:49 UTC, Wenn911 commented
Сделал

2022-11-15 13:57 UTC, dzencot commented
@Wenn911 посмотри плз конфликты

2022-11-15 15:46 UTC, closed without merging